name: Unit Tests

on:
  push:
    paths:
      - '**.kt'
      - '**.kts'
      - '**/gradle.properties'
      - '**/gradlew'
      - '**/gradlew.bat'
  pull_request:
    paths:
      - '**.kt'
      - '**.kts'
      - '**/gradle.properties'
      - '**/gradlew'
      - '**/gradlew.bat'

jobs:
  test_linux:
    name: Run unit tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew linuxX64Test --info

      - name: Run JVM tests
        run: ./gradlew jvmTest --info

  test_macos:
    name: Run unit tests on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew macosX64Test --info

      - name: Run JVM tests
        run: ./gradlew jvmTest --info

  test_windows:
    name: Run unit tests on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Run platform-specific tests
        run: ./gradlew.bat mingwX64Test --info

      - name: Run JVM tests
        run: ./gradlew.bat jvmTest --info
